Repository kzi-nastava/iss-project-event-planner-siit-2024-team-11, pull requests merged in 2024-11, with the labels that each got.

#3 Feature/student three models
  Eventy/src/main/java/org/example/eventy/common/models/ReservationConfirmationType.java
  Eventy/src/main/java/org/example/eventy/events/models/Budget.java
  Eventy/src/main/java/org/example/eventy/events/models/BudgetItem.java
  Eventy/src/main/java/org/example/eventy/interactions/model/Message.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Review.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Service.java
  Eventy/src/main/java/org/example/eventy/solutions/models/ServiceHistory.java
Labels: enhancement

#6 Feature/student three controllers
  Eventy/src/main/java/org/example/eventy/reviews/controllers/ReviewController.java
  Eventy/src/main/java/org/example/eventy/reviews/dtos/CreateReviewDTO.java
  Eventy/src/main/java/org/example/eventy/reviews/dtos/CreatedReviewDTO.java
  Eventy/src/main/java/org/example/eventy/reviews/models/Review.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/CategoryDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/PriceListDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ProductPurchaseDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/GetServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Service.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
Labels: enhancement

#7 Student Two - ENDPOINTS (Improvement)
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/EventCardDTO.java
  Eventy/src/main/java/org/example/eventy/events/services/EventService.java
  Eventy/src/main/java/org/example/eventy/reviews/controllers/ReviewController.java
  Eventy/src/main/java/org/example/eventy/reviews/dtos/ReviewDTO.java
  Eventy/src/main/java/org/example/eventy/reviews/models/Review.java
  Eventy/src/main/java/org/example/eventy/reviews/services/ReviewService.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ReservationController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ReservationDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionCardDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/GetServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Reservation.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Solution.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ReservationService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
  Eventy/src/main/java/org/example/eventy/users/models/User.java
Labels: improvement

#8 [FIX] Deleting is done with @DeleteMapping instead of @PutMapping
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
Labels: bug
