Repository kzi-nastava/iss-project-event-planner-siit-2024-team-11, pull requests merged in 2025-01, with the labels that each got.

#23 Fast Registration & Upgrade Profile - BACKEND
  Eventy/src/main/java/org/example/eventy/common/services/EmailService.java
  Eventy/src/main/java/org/example/eventy/common/util/ActiveUserManager.java
  Eventy/src/main/java/org/example/eventy/common/util/EncryptionUtil.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/models/Event.java
  Eventy/src/main/java/org/example/eventy/events/models/Invitation.java
  Eventy/src/main/java/org/example/eventy/events/repositories/InvitationRepository.java
  Eventy/src/main/java/org/example/eventy/events/services/InvitationService.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/ReportController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/FastRegistrationDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UpgradeProfileDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UserDTO.java
  Eventy/src/main/java/org/example/eventy/users/models/AuthenticatedUser.java
  Eventy/src/main/java/org/example/eventy/users/models/User.java
  Eventy/src/main/java/org/example/eventy/users/repositories/UserRepository.java
  Eventy/src/main/java/org/example/eventy/users/services/UserService.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidFastRegistration.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidUpgradeProfile.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/FastRegistrationValidator.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/UpgradeProfileValidator.java
Labels: enhancement

#24 Bugfix/email confirmation for mobile
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/util/NetworkUtils.java
Labels: bug

#25 Refactor/working with pictures
  Eventy/src/main/java/org/example/eventy/common/repositories/PictureRepository.java
  Eventy/src/main/java/org/example/eventy/common/services/PictureService.java
  Eventy/src/main/java/org/example/eventy/config/WebSecurityConfig.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/EventCardDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionCardDTO.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/RegistrationDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UpdateUserProfileDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UpgradeProfileDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UserDTO.java
Labels: refactor

#26 [BUGFIX] Fast Registration & Upgrade Profile - BACKEND
  Eventy/src/main/java/org/example/eventy/common/services/EmailService.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionRepository.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/FastRegistrationDTO.java
  Eventy/src/main/java/org/example/eventy/util/NetworkUtils.java
Labels: bug

#27 [IMPROVED] Category request acceptance, change, replacement
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionCategoryController.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionCategoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
Labels: improvement

#28 Improvement/solution categories fix
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionCategoryController.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionCategoryRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionCategoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
Labels: improvement
