Repository kzi-nastava/iss-project-event-planner-siit-2024-team-11, pull requests merged in 2025-02, with the labels that each got.

#30 Feature/solution details
  Eventy/src/main/java/org/example/eventy/config/WebSecurityConfig.java
  Eventy/src/main/java/org/example/eventy/events/dtos/BudgetItemDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionCardDTO.java
  Eventy/src/main/java/org/example/eventy/users/models/User.java
  Eventy/src/main/java/org/example/eventy/users/services/UserService.java
Labels: enhancement

#31 Feature/event stats
  Eventy/pom.xml
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventDownloadPDFController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/EventStatsDTO.java
  Eventy/src/main/java/org/example/eventy/events/repositories/EventRepository.java
  Eventy/src/main/java/org/example/eventy/events/services/EventService.java
  Eventy/src/main/java/org/example/eventy/reviews/repositories/ReviewRepository.java
  Eventy/src/main/java/org/example/eventy/reviews/services/ReviewService.java
  Eventy/src/main/resources/data.sql
Labels: enhancement

#33 [FIX] Add service function
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
Labels: enhancement

#34 Feature/product management
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/UpdateEventDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/CreateProductDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ProductDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/models/ProductHistory.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/ProductHistoryRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductHistoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductService.java
Labels: enhancement

#35 Improvement/services
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/ServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdatedServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
Labels: enhancement

#36 Refactor/solution toggling
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/CreateProductDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ProductDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
Labels: refactor

#37 [CHANGE] Added wrapper classes to DTOs to handle null values
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/CreateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/ServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/services/UpdateServiceDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
Labels: improvement

#38 [FIX] Event type in use deactivation
  Eventy/src/main/java/org/example/eventy/events/services/EventService.java
  Eventy/src/main/java/org/example/eventy/events/services/EventTypeService.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
Labels: bug

#39 Feature/product purchase
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ProductPurchaseDTO.java
Labels: enhancement

#40 Reviews (admin) - BACKEND
  Eventy/src/main/java/org/example/eventy/reviews/controllers/ReviewController.java
  Eventy/src/main/java/org/example/eventy/reviews/services/ReviewService.java
  Eventy/src/main/resources/data.sql
Labels: enhancement

#41 Reports - BACKEND
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/ReportController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/CreateReportDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/ReportDTO.java
  Eventy/src/main/java/org/example/eventy/users/models/Report.java
  Eventy/src/main/java/org/example/eventy/users/repositories/ReportRepository.java
  Eventy/src/main/java/org/example/eventy/users/services/ReportService.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidCreateReport.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/CreateReportValidator.java
Labels: enhancement

#42 Blocks - BACKEND
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/EventCardDTO.java
  Eventy/src/main/java/org/example/eventy/events/models/Event.java
  Eventy/src/main/java/org/example/eventy/events/repositories/EventRepository.java
  Eventy/src/main/java/org/example/eventy/events/services/EventService.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionService.java
  Eventy/src/main/java/org/example/eventy/users/controllers/ReportController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/BlockUserDTO.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidBlockUser.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/BlockUserValidator.java
  Eventy/src/main/resources/data.sql
Labels: enhancement, improvement
