Repository kzi-nastava/iss-project-event-planner-siit-2024-team-11, pull requests merged in 2025-07, with the labels that each got.

#49 Feature/budget
  Eventy/src/main/java/org/example/eventy/events/controllers/BudgetController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/BudgetDTO.java
  Eventy/src/main/java/org/example/eventy/events/dtos/BudgetItemDTO.java
  Eventy/src/main/java/org/example/eventy/events/models/BudgetItem.java
  Eventy/src/main/java/org/example/eventy/events/repositories/BudgetItemRepository.java
  Eventy/src/main/java/org/example/eventy/events/services/BudgetItemService.java
  Eventy/src/main/java/org/example/eventy/events/services/BudgetService.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ReservationController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionCategoryController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionDetailsDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/SolutionHistoryDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Product.java
  Eventy/src/main/java/org/example/eventy/solutions/models/ProductHistory.java
  Eventy/src/main/java/org/example/eventy/solutions/models/Service.java
  Eventy/src/main/java/org/example/eventy/solutions/models/ServiceHistory.java
  Eventy/src/main/java/org/example/eventy/solutions/models/SolutionHistory.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/ProductHistoryRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionCategoryRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionHistoryRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/repositories/SolutionRepository.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ProductHistoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceHistoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/ServiceService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionCategoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/services/SolutionHistoryService.java
  Eventy/src/main/java/org/example/eventy/solutions/validation/validator/ReservationValidator.java
  Eventy/src/main/resources/data.sql
Labels: enhancement

#51 Bugfix/configuring routing
  Eventy/src/main/java/org/example/eventy/config/WebSecurityConfig.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventTypeController.java
  Eventy/src/main/java/org/example/eventy/events/controllers/LocationController.java
  Eventy/src/main/java/org/example/eventy/interactions/controllers/ChatController.java
  Eventy/src/main/java/org/example/eventy/interactions/controllers/NotificationController.java
  Eventy/src/main/java/org/example/eventy/reviews/controllers/ReviewController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ReservationController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ServiceController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionCategoryController.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/SolutionController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/ReportController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
Labels: bug

#53 Improvement/adding validators
  Eventy/src/main/java/org/example/eventy/events/controllers/EventController.java
  Eventy/src/main/java/org/example/eventy/events/controllers/EventTypeController.java
  Eventy/src/main/java/org/example/eventy/events/dtos/CreatedEventTypeDTO.java
  Eventy/src/main/java/org/example/eventy/events/dtos/UpdateEventTypeDTO.java
  Eventy/src/main/java/org/example/eventy/events/validation/validator/OrganizedEventValidator.java
  Eventy/src/main/java/org/example/eventy/events/validation/validator/UpdateEventValidator.java
  Eventy/src/main/java/org/example/eventy/solutions/controllers/ProductController.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/CreateProductDTO.java
  Eventy/src/main/java/org/example/eventy/solutions/dtos/ProductDTO.java
  Eventy/src/main/java/org/example/eventy/users/controllers/AuthenticationController.java
  Eventy/src/main/java/org/example/eventy/users/controllers/UserProfileController.java
  Eventy/src/main/java/org/example/eventy/users/dtos/RegistrationDTO.java
  Eventy/src/main/java/org/example/eventy/users/dtos/UpdateUserProfileDTO.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidRegistration.java
  Eventy/src/main/java/org/example/eventy/users/validation/annotation/ValidUpdateUserProfile.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/RegistrationValidator.java
  Eventy/src/main/java/org/example/eventy/users/validation/validator/UpdateUserProfileValidator.java
Labels: improvement
